[default.user_inputs.general]
MC_iterations = 1000
country = "UK"
currency = "GBP"

[default.user_inputs.feedstock]
category = "herbaceous biomass"
name = "example"
particle_size_ar = 3.0
carbon = 45.0
hydrogen = 8.0
nitrogen = 2.0
sulphur = 0.1
oxygen = 44.9
moisture_ar = 18.0
moisture_post_drying = 12.0
ash = 7.0

[default.user_inputs.process_conditions]
gasification_temperature = 850.0
ER = 0.3
operation_mode = "Continuous"
operation_scale = "Lab"
catalyst = "No"
gasifying_agent = "Air"
reactor_type = "Fluidised bed"
bed_material = "Silica"

[default.user_inputs.system_size]
mass_basis_selected = true
power_feedstock_selected = true
power_electric_selected = true
mass_basis = 20
power_feedstock = 100
power_electric = 66
# FAKE VALUES CURRENTLY

[default.user_inputs.economic]
CEPCI_year = 2020
electricity_price_choice = "default"
heat_price_choice = "default"
biochar_price_choice = "user selected"
gate_fee_or_feedstock_price_selection = "gate fee"
gate_fee_or_feedstock_price_choice = "user selected"
carbon_tax_selection = true
carbon_tax_choice = "user selected"

[default.user_inputs.economic.electricity_price_parameters]

[default.user_inputs.economic.heat_price_parameters]

[default.user_inputs.economic.biochar_price_parameters]
lower = 50.0
mode = 100.0
upper = 200.0
distribution_type = "triangular"

[default.user_inputs.economic.gate_fee_or_feedstock_price_parameters]
low = 50.0
high = 100.0
distribution_type = "range"

[default.user_inputs.economic.carbon_tax_parameters]
mean = 75.0
std = 15.0
distribution_type = "gaussian"

[default.user_inputs.processes.milling]
included = false

[default.user_inputs.processes.drying]
included = true
moisture_post_drying = 12.0

[default.user_inputs.processes.pelleting]
included = false

[default.user_inputs.processes.bale_shredding]
included = false

[default.user_inputs.processes.biochar]
included = true

[default.user_inputs.processes.carbon_capture]
included = true
method = "VPSA post combustion"

[default.user_inputs.processes.CHP]
