[default]

[default.background]
# Random number seed
random_seed = 42

# Number of Monte Carlo iterations to be used by the model
iterations_MC = 1000

# Options for distribution types used in Monte Carlo simulation
distribution_options = ["fixed", "range", "triangular", "gaussian"]

# Default value how biogenic carbon is to be treated: 0 - completely biogenic (i.e. no net GWP); 1 - equivalent to fossil fuels
biogenic_carbon_equivalency = 0.0
# this can be changed later to different approaches ideally - i.e. normal 100 time horizon and biogenic carbon assumed as zero
# or a temporal approach - see supplementary material of 10.1007/s11367-020-01853-2 (e.g. S1 and S11)


[default.general]
# List of countries supported within the model
countries = ["UK", "EU", "Germany", "USA"]

# Broad feedstock categories supported in analysis and ML prediction model
feedstock_categories = ["plastics", "municipal solid waste", "herbaceous biomass", "woody biomass", "sewage sludge", "other"]

# Functional unit (FU) used in LCA
FU = 1000  # [kg] (i.e. 1 tonne of feedstock)
FU_label = "tonne of feedstock input"

[default.labels]
# Labels for model inputs array
input_data = ["C [%daf]", "H [%daf]", "S [%daf]", "Particle size [mm]", "Ash [%db]", "Moisture [%wb]",
    "Temperature [°C]", "Operation (Batch/Continuous)", "ER", 'Catalyst', "Scale", "Agent_air", "Agent_air + steam",
    "Agent_other", "Agent_oxygen", "Agent_steam", "Reactor_fixed bed", "Reactor_fluidised bed", "Reactor_other",
    "Bed_N/A", "Bed_alumina", "Bed_olivine", "Bed_other", "Bed_silica"]

output_data = ["N2 [vol.% db]", "H2 [vol.% db]", "CO [vol.% db]", "CO2 [vol.% db]", "CH4 [vol.% db]",
    "C2Hn [vol.% db]", "LHV [MJ/Nm3]", "Tar [g/Nm3]", "Gas yield [Nm3/kg wb]", "Char yield [g/kg wb]"]

output_units = ["[vol.% db]", '[vol.% db]', '[vol.% db]', '[vol.% db]', '[vol.% db]', '[vol.% db]', '[MJ/N$m^{3}$]',
    '[g/N$m^{3}$]', '[N$m^{3}$/kg wb]', '[g/kg wb]']

LCA_output_plotting_string = "[kg $CO_{2-eq} / FU$]"


[default.plotting]

[default.plotting.digital]
fig_size = [6.4, 4.8]
fig_dpi = 100
title_fontsize = 18
legend_fontsize_small = 12
legend_fontsize_large = 14
labels_fontsize = 14
ticks_fontsize = 12
marker_size = 50
legend_location = "upper right"

[default.plotting.poster]
fig_size = [12, 8]
fig_dpi = 100
title_fontsize = 32
legend_fontsize_small = 26
legend_fontsize_large = 30
labels_fontsize = 32
ticks_fontsize = 26
marker_size = 200
legend_location = "upper right"


[default.unit_conversions]
mmBtu_to_MJ = 1055.06  # One million British thermal units to MJ


[default.data]

[default.data.densities]
# Densities of different gas species
N2 = 1.165
H2 = 0.0832
CO = 1.14
CO2 = 1.98
CH4 = 0.656
C2H4 = 1.18
O2 = 1.323
natural_gas = 0.777
units = "kg/m3"


[default.data.molar_masses]
# Molar or molecular masses of different gas species and other elements
N2 = 28
H2 = 2
CO = 28
CO2 = 44
CH4 = 16
C2H4 = 28
H = 1
C = 12
N = 14
O = 16
H2O = 18
units = "g/mol"


[default.data.LHV]
# Lower heating values (LHV) of different gas species and other elements
CO = 12.633
CH4 = 35.883
H2 = 10.783
C2H4 = 59.457
natural_gas = 36.6
units = "MJ/m3"
source = " HEATING VALUE OF GASES FROM BIOMASS GASIFICATION Report prepared for: IEA Bioenergy Agreement, Task 20 - Thermal Gasification of Biomass Lars Waldheim, Torbjörn Nilsson TPS Termiska Processer AB May 2001"


[default.data.HHV]
# Higher heating values (HHV) of different gas species and other elements
CO = 12.633
CH4 = 39.819
H2 = 12.745
C2H4 = 63.414
natural_gas = 40.6
units = "MJ/m3"
source = " HEATING VALUE OF GASES FROM BIOMASS GASIFICATION Report prepared for: IEA Bioenergy Agreement, Task 20 - Thermal Gasification of Biomass Lars Waldheim, Torbjörn Nilsson TPS Termiska Processer AB May 2001"


[default.data.CO2_equivalents]
# Carbon dioxide equivalent factors
# Factors are based on the IPCC Sixth Assessment Report (AR6) and are for a 100-year time horizon
CO2_equ_factor = 1
CH4_fossil_equ_factor = 29.8
CH4_non_fossil_equ_factor = 27.2
N2O_equ_factor = 273

[default.data.CO2_equivalents.electricity]
# Carbon intensity of grid electricity
UK = 0.21233  # [kg CO2eq./kWh] Ref: https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2021
USA = 0.38  # [kg CO2eq./kWh] Ref: https://www.eia.gov/environment/emissions/carbon/
Germany = 0.385  # [kg CO2eq./kWh] Ref: https://www.statista.com/statistics/1290224/carbon-intensity-power-sector-germany/#:~:text=The%20carbon%20intensity%20of%20Germany's,%2FKWh)%20of%20electricity%20generated.

[default.data.CO2_equivalents.thermal_energy.natural_gas]
# Carbon intensity of thermal energy generation from natural gas
UK = 0.222  # [kg CO2eq./kWh] Ref: GaBi model "Natural gas use"
USA = 0.191 # https://www.eia.gov/totalenergy/data/monthly/archive/00352011.pdf

[default.data.CO2_equivalents.resource_requirements]
# Carbon intensity of various resource requirements
oxygen = 0.0913  # [kg CO2eq./kg O2] Ref: GaBi model "oxygen seperation"


[default.data.biogenic_fractions]
# Fraction of feedstock emissions considered biogenic
# Ref: See preliminary analysis done in \analysis\preliminary\biogenic_fraction_of_feedstocks.ipynb
"herbaceous biomass" = 0.9833
"woody biomass" = 0.9878
"municipal solid waste" = 0.65
"plastics" = 0


[default.data.feedstock_drying]
# Assumed room temperature and temperature of drying process
temp_drying_process = 40  # in deg C
room_temperature = 18  # in deg C

[default.data.feedstock_drying.dryer_efficiencies]
# Efficiencies of different dryer types
"Indirect-heated convection dryer" = 0.30
"Contact dryer" = 0.65
"Direct fired dryer" = 0.40  # energy generally supplied by natural gas (could use syngas)
"Microwave drying" = 0.50
"Solar drying" = 1  # unused value

[default.data.feedstock_drying.electricity_requirements]
# Electricity requirements for auxiliary processes (Note difference in units)
"GaBi (mean)" = 0.0037  # [kWh/kg of biomass input]
"Huber Belt dryer" = 0.0375  # [kWh/kg of water evaporation]
"Solar drying" = 0  # unused value

[default.data.milling]
screen_sizes = [3.20, 4.76, 6.50]  # mm

[default.data.specific_heats]
# Specific heat capacity of water
water = 4.186  # [kJ/kg K] at room temperature

[default.data.specific_heats.water_vapor]
# Specific heat of water vapour
"18 degC" = 1.86  # [kJ/kg K] at room temperature
"40 degC" = 1.87  # [kJ/kg K] at dryer temperature
"100 degC" = 1.89  # [kJ/kg K] at boiling temperature


[default.data.heats_vaporisation.water]
# Specific latent heat of vaporisation of water
"18 degC" = 2458  # [kJ/kg] at room temperature
"40 degC" = 2406  # [kJ/kg] at dryer temperature
"100 degC" = 2260  # [kJ/kg] at boiling temperature

[default.data.conversion_efficiencies]

[default.data.conversion_efficiencies.CHP]

[default.data.conversion_efficiencies.CHP.SOFC]
# CHP conversion efficiencies as decimals. Solid oxide fuel cell.
electrical = 0.35
heat = 0.55
parasitic = 0.02
size_kW = 1.7
make = "ISM Sunfire"
source = "https://doi.org/10.1016/j.wasman.2017.03.028"

[default.data.conversion_efficiencies.CHP.jenbacher_type_6]
# CHP conversion efficiencies as decimals. Jenbacher Type 6 gas engine.
 # Note: Much larger size than some of the other units.
electrical = 0.44
heat = 0.44
parasitic = 0
size_kW = 1634
make = "Jenbacher Type 6"
source = "https://www.innio.com/en/jenbacher/gas-engines/type-6"

[default.data.conversion_efficiencies.CHP.stirling_engine]
# CHP conversion efficiencies as decimals.
electrical = 0.12
heat = 0.80
parasitic = 0.02
size_kW = 1.2
make = "Whispergen WhisperTech"
source = "https://doi.org/10.1016/j.wasman.2017.03.028"

[default.data.conversion_efficiencies.CHP.micro_gas_turbine]
# CHP conversion efficiencies as decimals. Micro gas turbine .
electrical = 0.26
heat = 0.52
parasitic = 0.10
size_kW = 30
make = "Capstone Turbine Corporation"
source = "https://doi.org/10.1016/j.wasman.2017.03.028"


[default.data.power_requirements.air_separation_unit]
# Electricity requirements of an air seperation unit for the production of Oxygen.
"oxygen purity" = 0.95  # 95%
"power consumption" = 225  # [kW/ton O2] Note: Given as power not energy consumption.
source = "https://doi.org/10.1002/apj.354"

[default.data.energy_requirements.air_separation_unit.A]
# Electricity requirements of an air seperation unit for the production of Oxygen.
"energy consumption low" = 0.360  # [kWh/ Nm3 O2]
"energy consumption high" = 0.500  # [kWh/ Nm3 O2]
source = "Energy saving air-separation plant based on exergy analysis. Taniguchi, Masaaki; Asaoka, Hitoshi; Ayuhara, Toshiyuki. KOBELCO TECHNOLOGY REVIEW NO. 33 FEB. 2015"

[default.data.energy_requirements.air_separation_unit.B]
# Electricity requirements of an air seperation unit for the production of Oxygen.
"energy consumption" = 0.3056  # [kWh/ Nm3 O2]. Note: Given as 231kWh/tonne O2 in paper.
source = "https://doi.org/10.1016/j.ijggc.2013.10.009"

[default.data.energy_requirements.air_separation_unit.C]
# Electricity requirements for air seperation units for the production of Oxygen.
"energy consumption" = [0.280, 0.464, 0.639, 0.631]  # [kWh/ Nm3 O2]
source = "https://doi.org/10.4186/ej.2014.18.2.67"


# Economic data
[default.data.economic]

# TODO: Update if necessary
currencies = ["GBP", "USD", "EUR"]  # Currencies supported by the model
system_lifecycle = 20  # Life cycle of system [years]
reference_date = [2023, 1, 1]  # Reference date in year, month, day format.

[default.data.economic.interest_rate.year_2023]
GBP = 0.04
EUR = 0.03
USD = 0.045

# Also allow for call with countries
UK = 0.04
EU = 0.03
USA = 0.045

[default.data.economic.conversion_rates]  # Currency conversion rates

[default.data.economic.conversion_rates.year_2022]  # Annual averages
USD_TO_GBP = 0.8003
EUR_TO_GBP = 0.8489
source = "https://www.gov.uk/government/publications/exchange-rates-for-customs-and-vat-yearly"

[default.data.economic.electricity_wholesale_prices.UK]  # Electricity wholesale prices
lower = 0.080
mode = 0.110
upper = 0.200
units = "GBP/kWh"
distribution_type = "triangular"
source = ["https://tradingeconomics.com/united-kingdom/electricity-price",
    "https://www.ofgem.gov.uk/cy/energy-data-and-research/data-portal/wholesale-market-indicators"]

[default.data.economic.electricity_wholesale_prices.Germany]  # Electricity wholesale prices
lower = 0.080
mode = 0.110
upper = 0.200
units = "EUR/kWh"
distribution_type = "triangular"
source = ["https://tradingeconomics.com/germany/electricity-price"]

[default.data.economic.natural_gas_price.UK]  # Natural gas price
lower = 0.65
mode = 1.00
upper = 1.75
units = "GBP/thm"
distribution_type = "triangular"
source = ["https://tradingeconomics.com/commodity/uk-natural-gas"]

[default.data.economic.biochar_price.UK]  # biochar price
lower = 200
mode = 300
upper = 400
units = "GBP/tonne"
distribution_type = "triangular"
source = ["https://biochardemonstrator.ac.uk/info-for-farmers/#:~:text=How%20much%20does%20biochar%20cost,%C2%A37.99%20from%20Carbon%20Gold."]

[default.data.economic.carbon_price.UK]  # carbon trading prices
lower = 40
mode = 60
upper = 80
units = "GBP/tonne"
distribution_type = "triangular"
source = ["https://ember-climate.org/data/data-tools/carbon-price-viewer/", "https://www.statista.com/statistics/1322275/carbon-prices-united-kingdom-emission-trading-scheme/#:~:text=UK%2DETS%20carbon%20pricing%20in%20the%20United%20Kingdom%202022%2D2023&text=The%20price%20of%20emissions%20allowances,ton%20on%20May%2031%2C%202023."]

[default.data.economic.carbon_price.EU]  # carbon trading prices
lower = 65
mode = 85
upper = 100
units = "EUR/tonne"
distribution_type = "triangular"
source = ["https://ember-climate.org/data/data-tools/carbon-price-viewer/", "https://www.statista.com/statistics/1322214/carbon-prices-european-union-emission-trading-scheme/#:~:text=The%20price%20of%20emissions%20allowances,reform%20of%20the%20EU%20ETS."]


[default.data.economic.CEPCI]  # Chemical Enginnering Plant Cost Index (CEPCI) values
1995 = 381.1
1996 = 381.7
1997 = 386.5
1998 = 389.5
1999 = 390.6
2000 = 394.1
2001 = 394.3
2002 = 395.6
2003 = 402.0
2004 = 444.2
2005 = 468.2
2006 = 499.6
2007 = 525.4
2008 = 575.4
2009 = 521.9
2010 = 550.8
2011 = 585.7
2012 = 584.6
2013 = 567.3
2014 = 576.1
2015 = 556.8
2016 = 541.7
2017 = 567.5
2018 = 603.1
2019 = 619.2
2020 = 597.5
2021 = 708.8
2022 = 816.0
2023 = 803.3  # most recent value for June 2023 -
2024 = "unavailable"
2025 = "unavailable"
2026 = "unavailable"
2027 = "unavailable"
2028 = "unavailable"
2029 = "unavailable"
2030 = "unavailable"
sources = ["10.1016/J.ENCONMAN.2021.114631 (Fig. S1)", "10.1016/j.energy.2019.05.191", "10.1016/j.biortech.2020.123076"]


[default.streamlit]
economic_inputs_options = ["default", "user selected"]  # radio buttons for economic inputs
numeric_inputs_options = ["default", "user selected"]  # radio buttons for numeric inputs
pretreatment_options = ["Drying", "Milling", "Pelleting", "Bale shredding"]
carbon_capture_options = ["Vacuum pressure swing adsorption (VPSA) post combustion capture (default)",
                          "Amine-based post combustion capture"]
CHP_options = ["Jenbacher Type 6 gas engine (1600 kW) (default)", "Solid oxide fuel cell (SOFC) (1.7 kW)",
               "Stirling engine (1.2 kW)", "Micro gas turbine (30kW)", "User defined"]
dryer_type_options = ["Direct fired dryer", "Indirect-heated convection dryer", "Contact dryer", "Microwave drying",
                      "Solar drying"]
sensitivity_analysis_energy_options = ["default", "75 % of current emissions", "50 % of current emissions",
    "25 % of current emissions", "user defined"]
sensitivity_analysis_run_options = ['Use .toml file','Use new selection of parameters']
