# These are the first values loaded
[default]


[default.background]
# Random number seed
random_seed = 42

# Number of Monte Carlo iterations to be used by the model
iterations_MC = 1000


[default.general]
# List of countries supported within the model
countries = ["UK", "Germany", "USA", "World"]

# Broad feedstock categories supported in analysis and ML prediction model
feedstock_categories = ["plastics", "municipal solid waste", "herbaceous biomass", "woody biomass", "sewage sludge", "other"]

# Functional unit (FU) used in LCA
FU = 1000  # 1 tonne of feedstock


[default.labels]
# Labels for model inputs array
input_data = ["C [%daf]", "H [%daf]", "S [%daf]", "Particle size [mm]", "Ash [%db]", "Moisture [%wb]",
    "Temperature [°C]", "Operation (Batch/Continuous)", "ER", 'Catalyst', "Scale", "Agent_air", "Agent_air + steam",
    "Agent_other", "Agent_oxygen", "Agent_steam", "Reactor_fixed bed", "Reactor_fluidised bed", "Reactor_other",
    "Bed_N/A", "Bed_alumina", "Bed_olivine", "Bed_other", "Bed_silica"]

output_data = ["N2 [vol.% db]", "H2 [vol.% db]", "CO [vol.% db]", "CO2 [vol.% db]", "CH4 [vol.% db]",
    "C2Hn [vol.% db]", "LHV [MJ/Nm3]", "Tar [g/Nm3]", "Gas yield [Nm3/kg wb]", "Char yield [g/kg wb]"]

output_units = ["[vol.% db]", '[vol.% db]', '[vol.% db]', '[vol.% db]', '[vol.% db]', '[vol.% db]', '[MJ/N$m^{3}$]',
    '[g/N$m^{3}$]', '[N$m^{3}$/kg wb]', '[g/kg wb]']

LCA_output_plotting_string = "$kgCO_{2 eq.}FU^{-1}$"


[default.unit_conversions]
mmBtu_to_MJ = 1055.06  # One million British thermal units to MJ


[default.data]

[default.data.densities]
# Densities of different gas species
N2 = 1.165
H2 = 0.0832
CO = 1.14
CO2 = 1.98
CH4 = 0.656
C2H4 = 1.18
O2 = 1.323
units = "kg/m3"

[default.data.molar_masses]
# Molar or molecular masses of different gas species and other elements
N2 = 28
H2 = 2
CO = 28
CO2 = 44
CH4 = 16
C2H4 = 28
H = 1
C = 12
O = 16
H2O = 18
units = "g/mol"

[default.data.LHV]
# Lower heating values (LHV) of different gas species and other elements
CO = 12.633
CH4 = 35.883
H2 = 10.783
C2H4 = 59.457
units = "MJ/m3"
source = " HEATING VALUE OF GASES FROM BIOMASS GASIFICATION Report prepared for: IEA Bioenergy Agreement, Task 20 - Thermal Gasification of Biomass Lars Waldheim, Torbjörn Nilsson TPS Termiska Processer AB May 2001"

[default.data.HHV]
# Higher heating values (HHV) of different gas species and other elements
CO = 12.633
CH4 = 39.819
H2 = 12.745
C2H4 = 63.414
units = "MJ/m3"
source = " HEATING VALUE OF GASES FROM BIOMASS GASIFICATION Report prepared for: IEA Bioenergy Agreement, Task 20 - Thermal Gasification of Biomass Lars Waldheim, Torbjörn Nilsson TPS Termiska Processer AB May 2001"



[default.data.CO2_equivalents]
# Carbon dioxide equivalent factors
# Factors are based on the IPCC Sixth Assessment Report (AR6) and are for a 100-year time horizon
CO2_equ_factor = 1
CH4_fossil_equ_factor = 29.8
CH4_non_fossil_equ_factor = 27.2
N2O_equ_factor = 273


[default.data.CO2_equivalents.electricity]
# Carbon intensity of grid electricity
UK = 0.21233  # [kg CO2eq./kWh] Ref: https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2021
USA = 0.38  # [kg CO2eq./kWh] Ref: https://www.eia.gov/environment/emissions/carbon/

[default.data.CO2_equivalents.thermal_energy.natural_gas]
# Carbon intensity of thermal energy generation from natural gas
UK = 0.222  # [kg CO2eq./kWh] Ref: GaBi model "Natural gas use"

[default.data.CO2_equivalents.resource_requirements]
# Carbon intensity of various resource requirements
oxygen = 0.0913  # [kg CO2eq./kg O2] Ref: GaBi model "oxygen seperation"


[default.data.biogenic_fractions]
# Fraction of feedstock emissions considered biogenic
# Ref: See preliminary analysis done in C:\Users\2270577A\PycharmProjects\PhD_LCA_TEA\analysis\preliminary\biogenic_fraction_of_feedstocks.ipynb
"herbaceous biomass" = 0.9833
"woody biomass" = 0.9878


[default.data.feedstock_drying]
# Assumed room temperature and temperature of drying process
temp_drying_process = 40  # in deg C
room_temperature = 18  # in deg C

[default.data.feedstock_drying.dryer_efficiencies]
# Efficiencies of different dryer types
"Indirect-heated convection dryer" = 0.30
"Contact dryer" = 0.65
"Direct fired dryer" = 0.40  # energy generally supplied by natural gas (could use syngas)
"Microwave drying" = 0.50

[default.data.feedstock_drying.electricity_requirements]
# Electricity requirements for auxiliary processes (Note difference in units)
"GaBi (mean)" = 0.0037  # [kWh/kg of biomass input]
"Huber Belt dryer" = 0.0375  # [kWh/kg of water evaporation]


[default.data.specific_heats]
# Specific heat capacity of water
water = 4.186  # [kJ/kg K] at room temperature

[default.data.specific_heats.water_vapor]
# Specific heat of water vapour
"18 degC" = 1.86  # [kJ/kg K] at room temperature
"40 degC" = 1.87  # [kJ/kg K] at dryer temperature
"100 degC" = 1.89  # [kJ/kg K] at boiling temperature


[default.data.heats_vaporisation.water]
# Specific latent heat of vaporisation of water
"18 degC" = 2458  # [kJ/kg] at room temperature
"40 degC" = 2406  # [kJ/kg] at dryer temperature
"100 degC" = 2260  # [kJ/kg] at boiling temperature

[default.data.conversion_efficiencies]

[default.data.conversion_efficiencies.CHP]

[default.data.conversion_efficiencies.CHP.SOFC]
# CHP conversion efficiencies as decimals. Solid oxide fuel cell.
electrical = 0.35
heat = 0.55
parasitic = 0.02
size_kW = 1.7
make = "ISM Sunfire"
source = "https://doi.org/10.1016/j.wasman.2017.03.028"

[default.data.conversion_efficiencies.CHP.jenbacher_type_6]
# CHP conversion efficiencies as decimals. Jenbacher Type 6 gas engine.
 # Note: Much larger size than some of the other units.
electrical = 0.44
heat = 0.44
parasitic = 0
size_kW = 1634
make = "Jenbacher Type 6"
source = "https://www.innio.com/en/jenbacher/gas-engines/type-6"

[default.data.conversion_efficiencies.CHP.stirling_engine]
# CHP conversion efficiencies as decimals.
electrical = 0.12
heat = 0.80
parasitic = 0.02
size_kW = 1.2
make = "Whispergen WhisperTech"
source = "https://doi.org/10.1016/j.wasman.2017.03.028"

[default.data.conversion_efficiencies.CHP.micro_gas_turbine]
# CHP conversion efficiencies as decimals. Solid oxide fuel cell.
electrical = 0.26
heat = 0.52
parasitic = 0.10
size_kW = 30
make = "Capstone Turbine Corporation"
source = "https://doi.org/10.1016/j.wasman.2017.03.028"


[default.data.power_requirements.air_separation_unit]
# Electricity requirements of an air seperation unit for the production of Oxygen.
"oxygen purity" = 0.95  # 95%
"power consumption" = 225  # [kW/ton O2] Note: Given as power not energy consumption.
source = "https://doi.org/10.1002/apj.354"


[default.data.energy_requirements.air_separation_unit.A]
# Electricity requirements of an air seperation unit for the production of Oxygen.
"energy consumption low" = 0.360  # [kWh/ Nm3 O2]
"energy consumption high" = 0.500  # [kWh/ Nm3 O2]
source = "Energy saving air-separation plant based on exergy analysis. Taniguchi, Masaaki; Asaoka, Hitoshi; Ayuhara, Toshiyuki. KOBELCO TECHNOLOGY REVIEW NO. 33 FEB. 2015"

[default.data.energy_requirements.air_separation_unit.B]
# Electricity requirements of an air seperation unit for the production of Oxygen.
"energy consumption" = 0.3056  # [kWh/ Nm3 O2]. Note: Given as 231kWh/tonne O2 in paper.
source = "https://doi.org/10.1016/j.ijggc.2013.10.009"

[default.data.energy_requirements.air_separation_unit.C]
# Electricity requirements for air seperation units for the production of Oxygen.
"energy consumption" = [0.280, 0.464, 0.639, 0.631]  # [kWh/ Nm3 O2]
source = "https://doi.org/10.4186/ej.2014.18.2.67"