[default.user_inputs.general]
MC_iterations = 1000
country = "USA"
currency = "USD"
system_life_span = 30
annual_operating_hours_user_imputed = false

[default.user_inputs.feedstock]
category = "woody biomass"
name = "Sawdust"
particle_size_ar = 6.0
carbon = 51.0
hydrogen = 6.0
nitrogen = 0.08
sulphur = 0.04
oxygen = 42.88
LHV = 16.5
moisture_ar = 16.0
ash = 0.08

[default.user_inputs.process_conditions]
gasification_temperature = 810.0
ER = 0.27
operation_mode = "Continuous"
operation_scale = "Pilot"
catalyst = "No"
gasifying_agent = "Air"
reactor_type = "Fluidised bed"
bed_material = "Silica"

[default.user_inputs.system_size]
mass_basis_user_imputed = true
power_feedstock_user_imputed = true
power_electric_user_imputed = true
mass_basis_tonnes_per_hour = 5.4
power_feedstock_MW_feedstock_LHV = 22.5
power_electric_MW_el = 10.0

[default.user_inputs.economic]
CEPCI_year = 2018
rate_of_return_decimals = 0.036000000000000004
electricity_price_choice = "user selected"
heat_price_choice = "user selected"
biochar_price_choice = "user selected"
gate_fee_or_feedstock_price_selection = "feedstock cost"
gate_fee_or_feedstock_price_choice = "user selected"
carbon_tax_included = false

[default.user_inputs.economic.electricity_price_parameters]
# value = 0.1027  # selling price in study
value = 0.30  # estimate LCOE
distribution_type = "fixed"

[default.user_inputs.economic.heat_price_parameters]
value = 0.0
distribution_type = "fixed"

[default.user_inputs.economic.biochar_price_parameters]
value = 0.0
distribution_type = "fixed"

[default.user_inputs.economic.gate_fee_or_feedstock_price_parameters]
value = 50.0
distribution_type = "fixed"

[default.user_inputs.economic.carbon_tax_parameters]

[default.user_inputs.economic.CO2_transport_price_parameters]

[default.user_inputs.economic.CO2_storage_price_parameters]

[default.user_inputs.processes.milling]
included = false

[default.user_inputs.processes.drying]
included = false

[default.user_inputs.processes.pelleting]
included = false

[default.user_inputs.processes.bale_shredding]
included = false

[default.user_inputs.processes.biochar]
included = true

[default.user_inputs.processes.carbon_capture]
included = false

[default.user_inputs.processes.CHP]
