[default.user_inputs.general]
MC_iterations = 1000
country = "UK"
currency = "GBP"
system_life_span = 20
annual_operating_hours_user_imputed = true
annual_operating_hours = 8000

[default.user_inputs.feedstock]
category = "herbaceous biomass"
name = "Corn straw (Gai, Int. J. Hydrog 2012, 37, 4935-4944)"
particle_size_ar = 3.75
carbon = 43.83
hydrogen = 5.95
nitrogen = 0.97
sulphur = 0.12
oxygen = 45.01
moisture_ar = 18.0
moisture_post_drying = 6.17
ash = 5.93
LHV = 16.502

[default.user_inputs.process_conditions]
gasification_temperature = 900.0
ER = 0.18
operation_mode = "Continuous"
operation_scale = "Lab"
catalyst = "No"
gasifying_agent = "Steam"
reactor_type = "Fixed bed"
bed_material = "N/A"

[default.user_inputs.system_size]
mass_basis_user_imputed = true
power_feedstock_user_imputed = false
power_electric_user_imputed = false
mass_basis_tonnes_per_hour = 1.00
power_feedstock_MW_feedstock_LHV = 4.58
power_electric_MW_el = 1.80
#mass_basis_tonnes_per_hour = 2.00
#power_feedstock_MW_feedstock_LHV = 9.17
#power_electric_MW_el = 4.31






# FAKE VALUES CURRENTLY

[default.user_inputs.economic]
CEPCI_year = 2020
rate_of_return_decimals = 0.05
electricity_price_choice = "default"
heat_price_choice = "default"
carbon_tax_included = true
carbon_tax_choice = "default"
biochar_price_choice = "default"
gate_fee_or_feedstock_price_choice = "user selected"
gate_fee_or_feedstock_price_selection = "feedstock cost"
CO2_transport_price_choice = "default"
CO2_storage_price_choice = "default"

[default.user_inputs.economic.electricity_price_parameters]

[default.user_inputs.economic.carbon_tax_parameters]
mean = 75.0
std = 15.0
distribution_type = "gaussian"
# Fake values

[default.user_inputs.economic.biochar_price_parameters]
mean = 120.0
std = 30.0
distribution_type = "gaussian"
# Fake values

[default.user_inputs.economic.gate_fee_or_feedstock_price_parameters]
mean = 120.0
std = 30.0
distribution_type = "gaussian"
# Fake values

[default.user_inputs.economic.CO2_transport_price_parameters]

[default.user_inputs.economic.CO2_storage_price_parameters]

[default.user_inputs.processes.milling]
included = false

[default.user_inputs.processes.drying]
included = true
moisture_post_drying = 6.17

[default.user_inputs.processes.pelleting]
included = false

[default.user_inputs.processes.bale_shredding]
included = false

[default.user_inputs.processes.biochar]
included = true

[default.user_inputs.processes.carbon_capture]
included = true
method = "VPSA post combustion"
# method = "Amine post comb"

[default.user_inputs.processes.CHP]
type = "Jenbacher Type 6 gas engine (1600 kW) (default)"
