[default.user_inputs.general]
MC_iterations = 1000
country = "EU"
currency = "EUR"
system_life_span = 20
annual_operating_hours_user_imputed = false

[default.user_inputs.feedstock]
category = "woody biomass"
name = "Forest residues (estimated based on Phyllis #846"
particle_size_ar = 20.0
carbon = 52.39
hydrogen = 4.78
nitrogen = 1.07
sulphur = 0.11
oxygen = 41.65
LHV = 15.0
moisture_ar = 30.0
moisture_post_drying = 15.0
ash = 3.97
biogenic_carbon_fraction = 0.0

[default.user_inputs.process_conditions]
gasification_temperature = 750.0
ER = 0.3
operation_mode = "Continuous"
operation_scale = "Pilot"
catalyst = "No"
gasifying_agent = "Air"
reactor_type = "Fluidised bed"
bed_material = "Silica"

[default.user_inputs.system_size]
mass_basis_user_imputed = false
power_feedstock_user_imputed = true
power_electric_user_imputed = true
mass_basis_tonnes_per_hour = 0.24
power_feedstock_MW_feedstock_LHV = 1.0
power_electric_MW_el = 0.5

[default.user_inputs.economic]
CEPCI_year = 2010
rate_of_return_decimals = 0.05
electricity_price_choice = "user selected"
heat_price_choice = "user selected"
biochar_price_choice = "user selected"
gate_fee_or_feedstock_price_selection = "feedstock cost"
gate_fee_or_feedstock_price_choice = "user selected"
carbon_tax_included = false

[default.user_inputs.economic.electricity_price_parameters]
value = 0.044
distribution_type = "fixed"

[default.user_inputs.economic.heat_price_parameters]
value = 0.02
distribution_type = "fixed"

[default.user_inputs.economic.biochar_price_parameters]
value = 50.0
distribution_type = "fixed"

[default.user_inputs.economic.gate_fee_or_feedstock_price_parameters]
value = 50.0
distribution_type = "fixed"

[default.user_inputs.economic.carbon_tax_parameters]

[default.user_inputs.economic.CO2_transport_price_parameters]

[default.user_inputs.economic.CO2_storage_price_parameters]

[default.user_inputs.processes.milling]
included = true
screen_size_mm = 3.2

[default.user_inputs.processes.drying]
included = true
moisture_post_drying = 15.0

[default.user_inputs.processes.pelleting]
included = false

[default.user_inputs.processes.bale_shredding]
included = false

[default.user_inputs.processes.biochar]
included = true

[default.user_inputs.processes.carbon_capture]
included = false

[default.user_inputs.processes.CHP]
type = "User defined"
electrical_efficiency = 0.284
thermal_efficiency = 0.304
parasitic_demand = 0.1
size_kW = 250.0
